src/components/Icon.jsx
Added JSDocs with examples and updated to inherit color and use rem units.
=> updated Icon for flexibility and readability

src/components/Card.jsx, src/pages/Home.jsx
Creation of the card component, tested with a basic 3 card layout for functionality.  
Features:
- Accepts an image URL, image label, card header, and card description as props.
- Non-fixed size to work with different layouts and accept different lengths of text.
Possible Future Improvement:
- Image could be replaced with a dedicated image component.
Related issue: #4
=> Card Component (feature/card-component)

package.json, src/components/Footer.jsx, src/style/layouts.js, src/style/mediaQueries.js
Update footer style and added Icon component.
Add scroll to top logic.
=> updated footer style

src/components/Card.jsx, src/components/ServicesSection.jsx
Fixed the card component to remove extra unused space and improve responsiveness. This should be merged to #32 first.
Changes:
- Card layout uses a different grid row method to make the container fit to content.
- Fonts use clamp for size and line height to optimize appearance for mobile and desktop.
Relevant issue: #33
=> Card Responsiveness Fix (feature/card-update)

src/components/Card.jsx, src/components/ServicesSection.jsx, src/config/home.js, src/pages/Home.jsx
Created services section of the home page and added to home.jsx. Uses card component that's mapped based on content from config file. This should be merged to dev after merging #35. 
Features: 
- Responsive font size for section title and subtitle.
- Takes advantage of theme maxWidth for large screens.
- Layout is based on a 3 column grid that folds into 1 for mobile.
Other:
- Button style used is ghost, might need to create a version that's the same but gray like in the reference design. Not super important since the light blue color also looks ok. 
Now that this section has been created, it reveals that the card component is missing responsive font sizes causing extra space on some screen widths.
Relevant issue: #9
=> Home Page Services Section (feature/services-section)

src/components/MobileMenuButton.jsx, src/components/SampleHeader.jsx
Created a mobile nav menu button component (MobileMenuButton.jsx). Can be used in the same way as the current menu hamburger icon is with props. This pull request includes the implementation of the button into the sample header to demonstrate the functionalities of the button. Since it's mainly the component here, it can be inserted into the new header bar when it's time. 
Features: 
- Animated to transition from hamburger to X appearance.
- Self-hiding with media query to only appear on mobile.
- Uses aria-hidden attribute to hide purely visual elements for accessibility.
Related issues: #36 #30
=> Mobile Nav Menu Button (feature/mobile-nav)

src/App.js, src/components/MobileMenuButton.jsx, src/components/MobileNavMenu.jsx, src/components/SampleHeader.jsx, src/components/ScrollToTop.jsx, src/components/ToastContainer.jsx, src/config/navigation.js, src/style/indices.js, src/style/theme.js
Added new mobile nav menu.
Introduce indices in the theme for zIndex management throughout the site. 
`z-index: ${({ theme }) => theme.zIndices.mobileNavButton};`
Also added a navigation config file for links.
=> added mobile nav menu and indices

public/index.css, public/index.html, src/App.js
Created a temporary page for the site while it's in progress.
Features:
- Responsive text size
- Animated background gradient
Related issue: #25
=> Temporary Main Page (feature/main-placeholder)

src/components/organisms/ServicesInfo.jsx, src/components/templates/PageLayout.jsx, src/data/services.js, src/pages/Services.jsx
Created the services page with required components imported.
Features:
- Responsive layout
- Info tab area moved into separate component
- Info tabs populated with content from config
Comment:
- I used yarn lint to cleanup code this time and noticed it happened to modify files not related to this pull request which is why the files changed includes PageLayout.jsx
Related issue #57
=> Services Page (feature/services-page)

src/components/organisms/ServicesContact.jsx, src/components/organisms/ServicesSection.jsx, src/components/organisms/WhySection.jsx
Update buttons to link to pages
=> updated link on buttons

src/components/organisms/ContactCTA.jsx, src/pages/Home.jsx, src/pages/Services.jsx
Replaced the contact form on the home page with a simpler CTA to direct visitors to the dedicated contact page. The component is the same one as seen on the services page. 
Related issue #70
=> Home Contact Section (feature/home-contact)

src/components/molecules/InfoTab.jsx, src/components/organisms/ContactCTA.jsx, src/components/organisms/ServicesHero.jsx, src/style/layouts.js
Adjust mobile layout for Services page for improved appearance and user experience. 
Changes:
- sectionPadding in theme.layouts now includes variable vertical padding in addition to existing variable horizontal padding.
- Hero section now has a minimum height to make its appearance more consistent with what's seen on desktop.
- Info tab headers now have a smaller minimum font size for better readability on small screens.
- Contact CTA section header's minimum font size now matches the hero section's correctly.
Related issue #75
=> Services Page Mobile Layout (feature/services-mobile)

src/components/molecules/Card.jsx, src/components/molecules/WhyCard.jsx, src/components/organisms/ServicesSection.jsx, src/components/organisms/WhySection.jsx
Revised the home page's mobile layout and transition from desktop to improve user experience and consistency with rest of site. 
Changes: 
- Services section, cards, & why section's font sizes and spacings updated to match rest of site.
- Max width and section padding from site theme applied to why section.
Related Issue #75
=> Home Page Mobile Layout (feature/home-mobile)

src/components/molecules/NavMenu.jsx, src/components/organisms/Header.jsx, src/components/organisms/MobileNavMenu.jsx
Fixed the header/nav bar as laid out in the issue. 
Changes:
- Fixed fade in background color to show
- Updated fonts and hover colors on all links
- Updated padding and max width to match rest of site
- Formatted height
- Link logo to home page
Related issue #78
=> Header/Nav Bar Fix (feature/nav-bar)

src/components/organisms/Footer.jsx
Adjusted unexpanded footer (mini footer) to a smaller height and consolidated code. 
Changes:
- Mini footer height now 4rem instead of 6rem.
- Minor code consolidation and cleanup.
Related issue: #80
=> Footer Height Adjustment (feature/footer-height)

src/components/organisms/ContactCTA.jsx
Minor bug fix on the contact CTA component.
Changes:
- Remove unnecessary extra vertical padding.
Related issue: #75
=> Contact CTA Component Adjustment

src/components/organisms/HomeHero.jsx, src/pages/Home.jsx
Minor adjustment on the home hero component. 
Changes:
- Rename component to "HomeHero" for clarity.
- Add in vertical padding for small screens to avoid text overlap with menu bar.
Related Issue #75
=> Home Hero Adjustment (feature/home-hero-mobile)

src/components/organisms/ContactCTA.jsx, src/components/organisms/HomeHero.jsx
Resolved the get started button issue in the home hero to scroll to contact CTA section.
=> updated contact CTA link

src/style/layouts.js
Increased the vertical padding slightly by updating the layouts part of the theme file. 
Related issue #90
=> Adjust Vertical Padding (feature/vertical-padding)

src/components/organisms/InnerPageHero.jsx, src/components/organisms/PageHero.jsx, src/data/services.js, src/pages/Services.jsx
Creation of the hero component for the inner pages of the site. This is currently used on the services page and will also be applied to the new contact page and about page.
Features:
- Colors and text customizable through props.
- Allowed colors are hinted through prop validation.
- Default values for example purposes are assigned to required fields.
Related issue: #83
=> Inner Page Hero Component (feature/inner-page-hero)

src/components/organisms/ContactSection.jsx, src/components/organisms/PageCTA.jsx, src/data/home.js, src/data/services.js, src/pages/Home.jsx, src/pages/Services.jsx
Creation of the call to action banner component found at the bottom of each page. 
Features:
- Colors and text customizable through props.
- Allowed colors are hinted through prop validation.
- Default values for example purposes are assigned to required fields.
Related issue: #83
=> Page Call to Action Component (feature/page-cta)

src/style/colors.js
Updated the green shade to a new color. Slightly less neon, less saturated, and darker while keeping a similar feeling to the original. Still legible on blue backgrounds too.
Related issue #100
=> New Green (feature/green)

.gitignore, src/components/atoms/Shimmer.jsx, src/components/atoms/Textarea.jsx, src/components/molecules/Avatar.jsx, src/components/molecules/Card.jsx, src/components/organisms/ContactSection.jsx, src/components/organisms/HomeHero.jsx, src/components/organisms/ServicesInfo.jsx, src/components/organisms/ServicesSection.jsx, src/components/organisms/TestimonialsSection.jsx, src/components/organisms/WhySection.jsx, src/data/home.js, src/data/services.js, src/hooks/useContent.js, src/pages/Home.jsx, src/pages/Services.jsx
Cleaned up data fetching and implemented Firestore data for testimonials.
renamed config to content in the data configs
we will still have some content in the data file. Not all will go to Firebase
Implemented Shimmer loading.
=> Dataconfig cleanup

src/components/atoms/AuthLink.jsx, src/components/molecules/NavMenu.jsx, src/components/organisms/ContactInfo.jsx
Remove login link from header and kept in the footer.
=> remove login from header and kept in the footer

src/components/atoms/Input.jsx, src/pages/Login.jsx
=> Login page redesign

src/pages/404.jsx
Styled the 404 page and added a return to home link.
=> 404 Page (feature/404)

src/components/molecules/InfoTab.jsx, src/components/organisms/ServicesSection.jsx
Replaced the SectionInfo parts with the new TitleSubtitle component on the home page. A minor console bug with PropTypes was also fixed.
Related issue: #83
=> Add TitleSubtitle Component (feature/install-components)

src/components/atoms/Button.jsx, src/components/atoms/Input.jsx, src/components/atoms/Textarea.jsx, src/components/organisms/ContactForm.jsx, src/components/organisms/ContactSection.jsx, src/components/organisms/PageCTA.jsx, src/components/organisms/PageHero.jsx, src/data/contact.js, src/data/home.js, src/pages/Contact.jsx, src/pages/Login.jsx, src/style/buttons.js
A new contact page, built better with content moved into a new config file. 
Relate issue: #93
=> Contact page rebuild (feature/contact-page-v2)

src/components/molecules/Card.jsx, src/components/molecules/TitleSubtitle.jsx, src/components/organisms/ServicesSection.jsx, src/data/home.js
Update urls for services images
=> update images and update style

buildtools/copy-static.js, buildtools/generate-sitemap.js, package.json, public/robots.txt, public/sitemap.xml, src/components/molecules/SocialIcons.jsx, src/components/organisms/WhySection.jsx, src/pages/404.jsx, yarn.lock
Fixed several SEO related issues.
=> Push to prod

src/components/templates/SEO.jsx
=> added keywords

src/components/organisms/WhySection.jsx
Updated font size on Why section title for mobile.
=> Updated WhySection Font size

src/components/organisms/WhoWeAre.jsx, src/data/about.js, src/pages/About.jsx
Updated about.js to reflect proper title. Was previously showing Transpiled | About on both browser head and section heading. removed Title and added "Hero" instead.
=> Updated Title on Who we are page, wasnt reflecting correcly.

public/index.html, src/components/organisms/ContactForm.jsx, src/pages/Login.jsx
Added autocomplete props to forms
=> added autocomplete

public/index.css, src/components/atoms/MobileMenuButton.jsx, src/components/molecules/InfoTab.jsx, src/components/molecules/WhoCard.jsx, src/components/organisms/OurApproach.jsx, src/style/buttons.js, src/style/colors.js
Updated site colors for better readability and compatibility.
=> Improve Contrast Ratio

src/components/molecules/Card.jsx, src/components/molecules/TitleSubtitle.jsx, src/components/molecules/WhyCard.jsx, src/components/organisms/HomeHero.jsx, src/components/organisms/PageCTA.jsx, src/components/organisms/ServicesSection.jsx, src/components/organisms/WhySection.jsx, src/style/mixins.js
Type styles have now been added as mixins. I think this route makes more sense and offers more flexibility than a component while keeping the consistency. 
As a demonstration, only the home page has been updated but over time we can apply them to current and future additions.
=> Optimize type styles

src/components/molecules/Card.jsx, src/components/molecules/ServiceCardGrid.jsx, src/components/organisms/ServicesSection.jsx, src/data/home.js, src/hooks/useIsMobile.js
=> 175 update services section
